### ISSUE TITLE
Mover with remote pressure tracking

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#770]
When using static pressure reset controllers, the pressure at a remote point is controlled. To model this we currently need a control loop. Setting the remote pressure directly instead, would allow for some algebraic loops to be simplified. 
Therefore it would make sense to create a model that sets the remote pressure directly. I'll add such a model.

**Comment by Mathadon** [comment]
@mwetter it would probably make sense to integrate `FlowControlled_dpSystem` into `FlowControlled_dp` since it only involves parameter changes?

**Comment by mwetter** [comment]
The following is not clear or should be changed:
- [ ]  The input connector `p` should be called `pMea` to be clear that it is the measured pressure (and not a set point).
- [ ] The input connector `p` has quantity `Pressure`. Change to `AbsolutePressure` or `PressureDifference` (and make sure the displayUnit is `Pa` as some pressures are shown in bar).
- [ ] Having boolean parameters `setDownStreamPressure` and `setUpStreamPressure` makes no sense as a user could set both to `true`. This needs to be an enumeration.
- [ ] The unit test `FlowControlled_dpSystem` has `dp_nominal=500`, yet the fan is controlled to 1 Pascal. This does not make sense.
- [ ] The unit test `FlowControlled_dpSystem` mixes connects with equations, and uses an assert. We removed most asserts in the past as they caused problems in FMUs, so let's not reintroduce them.
- [ ] Review docs to fix errors such as `pressuredrop`.
- [ ]  Use the full name with a hyperlink in the info section of the example rather than `tests the use of <code>FlowControlled_dp</code>` as otherwise we will never detect if the name changes.
- [ ] Add this new functionality to `IBPSA.Fluid.Movers.UsersGuide`

**Comment by Mathadon** [comment]
@mwetter `IBPSA.Fluid.Sensors.Pressure` has 

```
  Modelica.Blocks.Interfaces.RealOutput p(final quantity="Pressure",
                                          final unit="Pa",
                                          min=0) "Pressure at port"
```

i.e. it has quantity `Pressure` and I'm getting warnings because the quantity is different. Should we change the sensor quantity or keep `Pressure` in `FlowControlled_dp`?

**Comment by mwetter** [comment]
I suggest to change the sensor quantity.
